### ISSUE TITLE
Rename variable subscriptionStorage to outboxStorage

### ISSUE THREAD

**Issue by maulik-modi** [rsivanov/Rebus.SqlServer.Outbox#3]
From
var subscriptionStorage = new SqlServerOutboxStorage(connectionFactory, tableName);

				if (automaticallyCreateTables)
				{
					subscriptionStorage.EnsureTableIsCreated();
				}

				return subscriptionStorage;

To
var outboxStorage= new SqlServerOutboxStorage(connectionFactory, tableName);

**Comment by rsivanov** [comment]
Fixed! Thank you.
